language: c++

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-7
    - g++-7

before_install:
- test -n $CC && unset CC
- sudo apt-get update
- sudo apt-get install -y libopenmpi-dev zlib1g-dev

script:
- export CC=gcc-7
- export CXX=g++-7
- rm -rf $HOME/deploy
- ./bootstrap.sh
- mkdir -p $HOME/deploy
- ./auto-install.py $HOME/deploy

branches:
    only:
     - master
